import auth from "@/api/requests/auth";
import { appUserAtom } from "@/atom";
import { useMutation } from "@tanstack/react-query";
import { useAtom } from "jotai";
import Head from "next/head";
import { useEffect } from "react";

export default function Home() {

  return (
    <>
      <Head>
        <title>Get Movie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen min-h-200 max-h-fit flex justify-center bg-lime-100 dark:bg-sky-900">
        <div className="w-3/4">

        </div>
      </div>
    </>
  );
}
