import admin from '@/api/admin';
import { useMutation } from '@tanstack/react-query';
import Head from 'next/head';
import React, { useEffect } from 'react'

const AdminPanel = () => {
  
  const getStatsMutation = useMutation(admin.getStats, {
    onSuccess(data){
      console.log(data);
    }
  });

  useEffect(()=>{
    getStatsMutation.mutate();
  },[])
  
  return (
    <>
      <Head>
        <title>Admin panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex max-h-fit min-h-screen justify-center bg-gradient-to-r from-violet-800 to-fuchsia-800 dark:bg-gradient-to-r dark:from-sky-900 dark:to-neutral-900 ">
        <div className="mt-24 mb-10 flex h-auto justify-center bg-neutral-500 bg-opacity-40 p-9 pb-10 dark:bg-neutral-700 dark:bg-opacity-50">
          <div>
         
          </div>
        </div>
      </div>
    </>
  )
}

export default React.memo(AdminPanel);

